name: CI

on:
  push:
    branches: 
      - main
  pull_request:
    types: 
      - opened
      - synchronize
      - ready_for_review
      - reopened

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Unit tests on node v${{ matrix.node-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node v${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install deps
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Run unit tests
        run: npm test

  lint:
    strategy:
      matrix:
        node-version: [22]

    name: Code checks on node v${{ matrix.node-version }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup node v${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install deps
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Biome check
        run: npm run check:ci

      - name: TypeScript type check
        run: npx tsc --noEmit
